### PR TITLE
Changes to support whatwg/fullscreen #43.

### PR DESCRIPTION
**Pull request by mounirlamouri**
Adding "triggered by user activation" to html-generated.json.
Adding screen-orientation.json with "triggered by a user generated
orientation change".

### CODE REVIEW

**Comment by mounirlamouri** [comment]
@annevk or @domenic PTAL :)

**Comment by domenic** [comment]
I know nothing about Anolis, sorry.

**Comment by mounirlamouri** [comment]
> I know nothing about Anolis, sorry.

Neither do I :)

**Comment by annevk** [comment]
This looks pretty good. But you need to add the HTML stuff to `html.json`, then run `html.py`.

**Comment by mounirlamouri** [comment]
@annevk PTAL. I've run `html.py` and it required to do some cleanup.

**Pull request merged**
